import re
import yaml
from typing import List
from pathlib import Path
import pandas as pd
from snakemake.utils import min_version, validate

min_version("5.1.0")


# ======================================================
# Config files
# ======================================================
configfile: "config.yaml"
validate(config, "schemas/config.schema.yaml")

samples = pd.read_csv(config["samples"]).set_index(["run_id", "sample_id"], drop=False)
validate(samples, "schemas/samples.schema.yaml")
# ======================================================
# Functions and Classes
# ======================================================


# ======================================================
# Global variables
# ======================================================
RULES_DIR = Path("rules")

files = []
for index, row in samples.iterrows():
    run_id = row["run_id"]
    if pd.isnull(run_id):
        continue
    sample_id = row["sample_id"]

    files.extend(
        [
            "data/{run}/stats/{sample}.stats.txt".format(sample=sample_id, run=run_id),
            "data/{run}/plots/{sample}.filtered.pdf".format(
                sample=sample_id, run=run_id
            ),
            "data/{run}/centrifuge/centrifuge_classification_{run}_{sample}.kreport".format(
                sample=sample_id, run=run_id
            ),
            "data/{run}/bracken/bracken_classification_{run}_{sample}.bracken".format(
                sample=sample_id, run=run_id
            ),
            "data/{run}/bracken/bracken_16s_classification_{run}_{sample}.bracken".format(
                sample=sample_id, run=run_id
            ),
            "data/{run}/bracken/bracken_16s_k21_classification_{run}_{sample}.bracken".format(
                sample=sample_id, run=run_id
            ),
            "data/{run}/centrifuge/centrifuge_16s_classification_{run}_{sample}.kreport".format(
                sample=sample_id, run=run_id
            ),
        ]
    )

#======================================================
# Rules
#======================================================
rule all:
    input: files

# the snakemake files that run the different parts of the pipeline
include: str(RULES_DIR.joinpath("porechop.smk"))
include: str(RULES_DIR.joinpath("filtlong.smk"))
include: str(RULES_DIR.joinpath("reports.smk"))
include: str(RULES_DIR.joinpath("kraken2.smk"))
include: str(RULES_DIR.joinpath("centrifuge.smk"))
include: str(RULES_DIR.joinpath("bracken.smk"))
